#!/usr/bin/env bash
LC_ALL=C
git fetch -p
local_branch="$(git rev-parse --abbrev-ref HEAD)"
feature_branches="$(git for-each-ref --format "%(refname)|" refs/remotes/origin/features/ | cut -c30-)"
feature_branches="${feature_branches//[$'\t\r\n ']}"
feature_branches="${feature_branches::-1}"
valid_branch_regex="^((features|bugs|hotfix|release|$feature_branches)\/)?[a-z0-9-]+$"
message="Your branch name is incorrect, your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
